# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(598, 355)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        Form.setFont(font)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_header = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.verticalLayout.addWidget(self.label_header)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.group_shell = QtWidgets.QGroupBox(Form)
        self.group_shell.setAlignment(QtCore.Qt.AlignCenter)
        self.group_shell.setObjectName("group_shell")
        self.gridLayout = QtWidgets.QGridLayout(self.group_shell)
        self.gridLayout.setObjectName("gridLayout")
        self.text_shell = QtWidgets.QTextBrowser(self.group_shell)
        self.text_shell.setObjectName("text_shell")
        self.gridLayout.addWidget(self.text_shell, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.group_shell)
        self.group_camera = QtWidgets.QGroupBox(Form)
        self.group_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.group_camera.setObjectName("group_camera")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_camera)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.canvas = Viewer(self.group_camera)
        self.canvas.setObjectName("canvas")
        self.gridLayout_2.addWidget(self.canvas, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.group_camera)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_header.setText(_translate("Form", "树莓派人脸识别门禁系统(by:官腾)"))
        self.group_shell.setTitle(_translate("Form", "信息栏"))
        self.group_camera.setTitle(_translate("Form", "摄像头"))
from widget_image_viewer import Viewer
